# Notebook of creating pandas Dataframe with possible features to train some Neural Network

In [1]:
import librosa
import numpy as np
import pandas as pd

In [4]:
example_features = pd.read_csv('../datasets/fma/fma_metadata/features.csv')

C:\Users\szyme\AppData\Local\Temp\ipykernel_52900\3217621105.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,

In [6]:
example_features.head()

feature       chroma_cens     chroma_cens.1     chroma_cens.2  \
0  statistics          kurtosis          kurtosis          kurtosis   
1      number                01                02                03   
2    track_id               NaN               NaN               NaN   
3           2  7.1806526184e+00  5.2303090096e+00  2.4932080507e-01   
4           3  1.8889633417e+00  7.6053929329e-01  3.4529656172e-01   

      chroma_cens.3     chroma_cens.4     chroma_cens.5     chroma_cens.6  \
0          kurtosis          kurtosis          kurtosis          kurtosis   
1                04                05                06                07   
2               NaN               NaN               NaN               NaN   
3  1.3476201296e+00  1.4824777842e+00  5.3137123585e-01  1.4815930128e+00   
4  2.2952005863e+00  1.6540306807e+00  6.7592434585e-02  1.3668476343e+00   

      chroma_cens.7     chroma_cens.8  ...        tonnetz.39  \
0          kurtosis          kurtosis  ...               std   
1                08                09  ...                04   
2               NaN               NaN  ...               NaN   
3  2.6914546490e+00  8.6686819792e-01  ...  5.4125156254e-02   
4  1.0540937185e+00  1.0810308903e-01  ...  6.3831120729e-02   

         tonnetz.40        tonnetz.41               zcr             zcr.1  \
0               std               std          kurtosis               max   
1                05                06                01                01   
2               NaN               NaN               NaN               NaN   
3  1.2225749902e-02  1.2110591866e-02  5.7588901520e+00  4.5947265625e-01   
4  1.4211839065e-02  1.7740072682e-02  2.8246941566e+00  4.6630859375e-01   

              zcr.2             zcr.3             zcr.4             zcr.5  \
0              mean            median               min              skew   
1                01                01                01                01   
2               NaN               NaN               NaN               NaN   
3  8.5629448295e-02  7.1289062500e-02  0.0000000000e+00  2.0898721218e+00   
4  8.4578499198e-02  6.3964843750e-02  0.0000000000e+00  1.7167237997e+00   

              zcr.6  
0               std  
1                01  
2               NaN  
3  6.1448108405e-02  
4  6.9330163300e-02  

[5 rows x 519 columns]

In [7]:
print(example_features.columns)

Index(['feature', 'chroma_cens', 'chroma_cens.1', 'chroma_cens.2',
       'chroma_cens.3', 'chroma_cens.4', 'chroma_cens.5', 'chroma_cens.6',
       'chroma_cens.7', 'chroma_cens.8',
       ...
       'tonnetz.39', 'tonnetz.40', 'tonnetz.41', 'zcr', 'zcr.1', 'zcr.2',
       'zcr.3', 'zcr.4', 'zcr.5', 'zcr.6'],
      dtype='object', length=519)


# Possible Features
For every linear feature we can extend received information by calculating:
- mean
- std
- median
- min
- max

For 2d arrays we can calculate it by some axises. For example 12 times Chroma Features.

In [20]:
def calculate_futures(name, values):
    return

In [40]:
y, sr = librosa.load('../datasets/fma/fma_small/Hip-Hop/000002.mp3')

## Chroma stft

In [41]:
chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr, n_chroma=12)
# np.mean(chroma_stft, axis=1)
# np.std(chroma_stft, axis=1)
np.median(chroma_stft, axis=1)
# np.min(chroma_stft, axis=1)
# np.max(chroma_stft, axis=1)

array([0.9196675 , 0.40637162, 0.29712954, 0.2745009 , 0.21831428,
       0.15204579, 0.19741958, 0.35440284, 0.29297513, 0.27465728,
       0.3117491 , 0.48450035], dtype=float32)

## Chroma cqt

In [42]:
chroma_cqt = librosa.feature.chroma_cqt(y=y, sr=sr, n_chroma=12)
# np.mean(chroma_cqt, axis=1)
# np.std(chroma_cqt, axis=1)
np.median(chroma_cqt, axis=1)
# np.min(chroma_cqt, axis=1)
# np.max(chroma_cqt, axis=1)

array([1.        , 0.6880701 , 0.64463836, 0.584162  , 0.61623794,
       0.6833725 , 0.5926604 , 0.5920069 , 0.46416956, 0.4784519 ,
       0.5086422 , 0.59332347], dtype=float32)

## Chroma cens

In [44]:
chroma_cens = librosa.feature.chroma_cens(y=y, sr=sr)
np.mean(chroma_cqt, axis=1)
# np.std(chroma_cqt, axis=1)
# np.median(chroma_cqt, axis=1)
# np.min(chroma_cqt, axis=1)
# np.max(chroma_cqt, axis=1)

array([0.95442134, 0.6741008 , 0.6360631 , 0.5646451 , 0.5884082 ,
       0.6486219 , 0.594884  , 0.5931008 , 0.4669653 , 0.48265433,
       0.5040411 , 0.5801074 ], dtype=float32)

## MFCC

In [56]:
mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=12)
np.mean(mfccs, axis=1)
# np.std(mfccs, axis=1)
# np.median(mfccs, axis=1)
# np.min(mfccs, axis=1)
# np.max(mfccs, axis=1)

array([-66.78069   ,  64.261795  ,  -9.776764  ,  11.287591  ,
        -2.4191437 ,   9.037897  ,  -1.1133189 ,   4.5498395 ,
        -5.305121  ,   0.24452747,  -9.495332  ,   2.5823383 ],
      dtype=float32)

# Rms

In [64]:
S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)
np.mean(rms, axis=1)
# np.std(rms, axis=1)
# np.median(rms, axis=1)
# np.min(rms, axis=1)
# np.max(rms, axis=1)

array([0.08595273], dtype=float32)

# Spectral centroid

In [68]:
cent = librosa.feature.spectral_centroid(y=y, sr=sr)
np.mean(cent, axis=1)
# np.std(cent, axis=1)
# np.median(cent, axis=1)
# np.min(cent, axis=1)
# np.max(cent, axis=1)

array([3056.58789738])

# P’th-order spectral bandwidth

In [69]:
spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)